version: '3.3'

volumes:
  vendor:
    driver: local
  storage:
    driver: local
  bootstrap-cache:
    driver: local

services:

  backend:
    env_file:
      - .envs/apache.env
      - .envs/php-ini.env
      - .envs/http-proxy.env
      - .envs/app.env
    ports:
      - ${APPLICATION_RUNNING_PORT}:8099
      - ${APPLICATION_RUNNING_HTTPS_PORT}:8499
    volumes:
      - ../:/var/www/html
